# Generated by Django 5.2.1 on 2025-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taille', models.IntegerField()),
                ('duree_de_vie', models.IntegerField()),
                ('environnement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taille', models.IntegerField()),
                ('duree_de_vie', models.IntegerField()),
                ('environnement', models.CharField(max_length=100)),
            ],
        ),
    ]
